### ISSUE TITLE
Question about tokenization

### ISSUE THREAD

**Issue by thibault-formal** [McGill-NLP/llm2vec#26]
Hey,
Great work!
I am trying to use your models in a different codebase, and I want to be sure I get things correctly. I am not 100% sure of what is happening in the `tokenize` function (the part with `texts_2`), could you clarify this?
Thx!

**Comment by ParishadBehnam** [comment]
Hi,

Thanks for your interest in our work.
Please note that we append instructions to the texts via a sequence of special characters in the `_convert_to_str` function. In the `tokenize` function, we use `texts_2` to keep the texts only and tokenize them as well to modify the masks, in order to be able to skip the embeddings of the instruction tokens when performing the pooling.

Please let us know if you have any other questions.
