### ISSUE TITLE
The reason of inserting strings to text in _convert_to_str

### ISSUE THREAD

**Issue by tma15** [McGill-NLP/llm2vec#29]
Hi, could you explain the reason of inserting strings `!@#$%^&*` to the original text in `_convert_to_str`?

https://github.com/McGill-NLP/llm2vec/blob/main/llm2vec/llm2vec.py#L254

```py
    def _convert_to_str(self, instruction, text):
        # ...
        return f"{instruction.strip()} !@#$%^&*(){text}"
```

**Comment by ParishadBehnam** [comment]
Hi,

Sure. Following other concurrent work recipe, we only take the representation of the input text during the pooling. In other words, the instruction tokens affect the representation of the input text (e.g., queries), and in the pooling step, we only take the representation of the input text into account. 

Therefore, we add a special separator so that in the tokenize function we can define an `embed_mask` so we mask out the instruction tokens flawlessly when pooling. 

Please let us know if you need more explanation on this.

**Comment by tma15** [comment]
Thanks! That makes sense.
