### ISSUE TITLE
impact of MNTP

### ISSUE THREAD

**Issue by zhaobinNF** [McGill-NLP/llm2vec#5]
What is the impact of MNTP? Have you ever evaluate the result of directly using BI + SimCSE?

**Comment by ParishadBehnam** [comment]
Hi, 
SimCSE itself is required for sentence representation, but MNTP is a word-level training, and we found it to be pretty much required for the models to learn how to utilize bidirectional attention. You may find some results on the performance of Bi+SimCSE models in Table 4 and Table 5 of the paper (in the Appendix). Since MTEB is a large benchmark to evaluate models on, we only evaluated Bi+SimCSE on the MTEB subset, as explained in the paper.
