### ISSUE TITLE
Clarification on the example loading base Mistral MNTP and applying MNTP adapter

### ISSUE THREAD

**Issue by chrisconst01** [McGill-NLP/llm2vec#55]
My goal is to load your pretrained bidirectional model and fine-tune on my dataset using your code.

I am following the example from [here](https://huggingface.co/McGill-NLP/LLM2Vec-Meta-Llama-3-8B-Instruct-mntp-unsup-simcse)
```python
model = AutoModel.from_pretrained(
    "McGill-NLP/LLM2Vec-Meta-Llama-3-8B-Instruct-mntp",
    trust_remote_code=True,
    config=config,
    torch_dtype=torch.bfloat16,
    device_map="cuda" if torch.cuda.is_available() else "cpu",
)
model = PeftModel.from_pretrained(
    model,
    "McGill-NLP/LLM2Vec-Meta-Llama-3-8B-Instruct-mntp",
)
model = model.merge_and_unload()  # This can take several minutes on cpu

# Loading unsupervised SimCSE model. This loads the trained LoRA weights on top of MNTP model. Hence the final weights are -- Base model + MNTP (LoRA) + SimCSE (LoRA).
model = PeftModel.from_pretrained(
    model, "McGill-NLP/LLM2Vec-Meta-Llama-3-8B-Instruct-mntp-unsup-simcse"
)
```

Is it loading the base MNTP model and then applying on top the MNTP lora adapter? Isn't this duplicate since it is already pretrained on the MNTP task? Why apply again the MNTP adapters?

I tried doing one more `merge_and_unload()` after loading the SimCSE adapter and then save the model but I get an error: `local variable 'active_adapters' referenced before assignment` similar to this [issue](https://github.com/huggingface/transformers/issues/26972)

This error would go away if I loaded the base Mistral model first with `AutoModel.from_pretrained("mistralai/Mistral-7B-Instruct-v0.2")`, but I am not sure if that would enable bidirectional attention and it is the correct way to load this model.

**Comment by vaibhavad** [comment]
> tried doing one more merge_and_unload() after loading the SimCSE adapter and then save the model but I get an error: local variable 'active_adapters' referenced before assignment similar to [this](https://github.com/huggingface/transformers/issues/26972)

The issue seems similar to [this](https://huggingface.co/McGill-NLP/LLM2Vec-Mistral-7B-Instruct-v2-mntp-unsup-simcse/discussions/1#66178d42b4c8242669744216). You can use the proposed workaround until HF pushes a fix. The workaround is also present inside llm2vec [save](https://github.com/McGill-NLP/llm2vec/blob/main/llm2vec/llm2vec.py#L374) function.



> Is it loading the base MNTP model and then applying on top the MNTP lora adapter? Isn't this duplicate since it is already pretrained on the MNTP task? Why apply again the MNTP adapters?

It is first loading the original Llama-3 model with the custom code that enables bidirectional connections. Next, it is loading the actual PEFT model. This combination of custom code + PEFT is not really documented anywhere, we just discovered that it works through trial and error. It is very convenient for us as then we don't have to upload the merged model and face License issues.

Side note: In my opinion, [loading via llm2vec](https://github.com/McGill-NLP/llm2vec/tree/main?tab=readme-ov-file#preparing-the-model) library is much more simpler and easier to understand.
