### ISSUE TITLE
Error in _update_causal_mask while running the example code

### ISSUE THREAD

**Issue by aldrinjenson** [McGill-NLP/llm2vec#82]
Hi thanks for this project!
I tried running the example code on my nvidia GPU and also separately on a google colab notebook 

Each time when running the encode command `q_reps = l2v.encode(queries)`, I am getting the following error: 
`TypeError: LlamaBiModel._update_causal_mask() takes from 4 to 5 positional arguments but 6 were given`

Note that I am running the same code as in the readMe example.

<img width="1452" alt="image" src="https://github.com/McGill-NLP/llm2vec/assets/53407417/b20bd639-f6d6-4a89-a598-93a9284ee752">

I remember testing this same code a week before and at that time it was working perfectly.
Please let me know if this is because of some recent changes being made in pypi about any dependency libraries; or if there's any other way I can get this running fine.

Thank You!

**Comment by vaibhavad** [comment]
Hi @aldrinjenson,

This issue occurs with transformers version > 4.40 and llm2vec version < 0.15. [Here](https://github.com/McGill-NLP/llm2vec/issues/33#issuecomment-2087621074) is the link to discussion. Please make sure you are using the latest version of llm2vec.

If the issue still persists, do let me know the version of llm2vec and transformers, so that I can try to replicate the issue

**Comment by aldrinjenson** [comment]
> pip install llm2vec==0.1.8

This worked.
Thanks @vaibhavad !!
