### ISSUE TITLE
What are these sentence preprocessing used for?

### ISSUE THREAD

**Issue by ShengYun-Peng** [McGill-NLP/llm2vec#95]
https://github.com/McGill-NLP/llm2vec/blob/faa365e94e31cf6c5794144411682e687e4e03e0/llm2vec/llm2vec.py#L297C7-L301C70

It reads like these lines are never used in the training and inference. Plus, what is MEDI version of MTEB?

**Comment by vaibhavad** [comment]
They are used when evaluating on MTEB. Line 300-301 is used when documents are passed without any instructions, so that the code after this point is standardized to deal with both queries with instructions and documents without instruction. 

> what is MEDI version of MTEB?

I think this can be ignored. It just means MTEB with instructions.

**Comment by vaibhavad** [comment]
Closing as it is stale. Feel free to re-open if you have any more questions.

**Comment by vaibhavad** [comment]
Closing as it is stale. Feel free to re-open if you have any more questions.
